<h2>V4U Slick Slider</h2>
    <ul class="my-list">
        <li>1st Element</li>
        <li>2nd Element</li>
        <li>3rd Element</li>
        <li>4th Element</li>
        <li>5th Element</li>
        <li>6th Element</li>
        <li>7th Element</li>
        <li>8th Element</li>
    </ul>

<script>
   require([
      'jquery',
      'slick',
      'domReady!'
   ], function ($) {
$('.my-list').slick({
  dots: true,
  infinite: false,
  speed: 300,
  slidesToShow: 4,
  slidesToScroll: 4,
  responsive: [
    {
      breakpoint: 1024,
      settings: {
        slidesToShow: 3,
        slidesToScroll: 3,
        infinite: true,
        dots: true
      }
    },
    {
      breakpoint: 600,
      settings: {
        slidesToShow: 2,
        slidesToScroll: 2
      }
    },
    {
      breakpoint: 480,
      settings: {
        slidesToShow: 1,
        slidesToScroll: 1
      }
    }
  ]
});

   });
</script>